"""question_centric_architecture

Revision ID: 7407fb0efac7
Revises: 
Create Date: 2026-06-08 05:49:03.431021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7407fb0efac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_topic_link',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    
    # Custom Data Migration: Move existing topics to the link table
    op.execute("INSERT INTO question_topic_link (question_id, topic_id) SELECT question_id, topic_id FROM question_bank WHERE topic_id IS NOT NULL")
    
    op.drop_constraint(op.f('question_bank_topic_id_fkey'), 'question_bank', type_='foreignkey')
    op.drop_column('question_bank', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Custom Data Migration: Restore one topic per question
    op.execute("""
        UPDATE question_bank 
        SET topic_id = qtl.topic_id 
        FROM (SELECT question_id, MIN(topic_id) as topic_id FROM question_topic_link GROUP BY question_id) qtl 
        WHERE question_bank.question_id = qtl.question_id
    """)
    op.execute("DELETE FROM question_bank WHERE topic_id IS NULL")
    op.alter_column('question_bank', 'topic_id', nullable=False)
    
    op.create_foreign_key(op.f('question_bank_topic_id_fkey'), 'question_bank', 'topics', ['topic_id'], ['topic_id'], ondelete='CASCADE')
    op.drop_table('question_topic_link')
    # ### end Alembic commands ###
