"""Refactor HODLink and Subject to use ID based linking

Revision ID: c9c56d699e66
Revises: 
Create Date: 2026-06-03 12:07:36.430127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c56d699e66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add new columns (nullable initially for hod_link to allow data migration)
    op.add_column('hod_link', sa.Column('allowed_subject_id', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('allowed_subject_id', sa.Integer(), nullable=True))

    # 2. Data Migration: Ensure all existing subject_names have an allowed_subject entry
    op.execute("""
        INSERT INTO allowed_subjects (subject_name, is_active, created_at, updated_at)
        SELECT DISTINCT subject_name, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM (
            SELECT subject_name FROM hod_link
            UNION
            SELECT subject_name FROM subjects WHERE subject_name IS NOT NULL
        ) AS unique_names
        WHERE subject_name NOT IN (SELECT subject_name FROM allowed_subjects)
    """)
    
    # 3. Data Migration: Update references
    op.execute("""
        UPDATE hod_link
        SET allowed_subject_id = (
            SELECT allowed_subject_id FROM allowed_subjects WHERE allowed_subjects.subject_name = hod_link.subject_name
        )
    """)
    op.execute("""
        UPDATE subjects
        SET allowed_subject_id = (
            SELECT allowed_subject_id FROM allowed_subjects WHERE allowed_subjects.subject_name = subjects.subject_name
        )
    """)
    
    # 4. Make hod_link.allowed_subject_id non-nullable now that data is migrated
    op.alter_column('hod_link', 'allowed_subject_id', existing_type=sa.Integer(), nullable=False)
    
    # 5. Handle Constraints and dropping the old column
    # In postgres, dropping a column that is part of a PK will also drop the PK.
    # We will let Alembic handle dropping the column, which should be fine for Postgres.
    op.create_foreign_key(None, 'hod_link', 'allowed_subjects', ['allowed_subject_id'], ['allowed_subject_id'], ondelete='CASCADE')
    op.drop_column('hod_link', 'subject_name')
    
    op.create_foreign_key(None, 'subjects', 'allowed_subjects', ['allowed_subject_id'], ['allowed_subject_id'], ondelete='SET NULL')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'allowed_subject_id')
    op.add_column('hod_link', sa.Column('subject_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hod_link', type_='foreignkey')
    op.drop_column('hod_link', 'allowed_subject_id')
    # ### end Alembic commands ###
