"""Add pdf_url column to grade_config table

Revision ID: add_grade_pdf_url
Revises: add_question_status_ts
Create Date: 2026-03-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_grade_pdf_url'
down_revision = 'add_question_status_ts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade_config', sa.Column('pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade_config', 'pdf_url')
    # ### end Alembic commands ###
